version: '3.9'

services:
  app:
    build:
    container_name: food_app
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    ports:
      -"5000:5000"

mysql:
  image: mysql:8
  restart: always
  environemnt:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: food_app

  ports:
   -"3306:3306"


redis:
  image: redis:7
  ports:
    -"6379:6379"